refactor: Rewrite all scripts

diff --git a/Genshin Impact/run_launcher b/Genshin Impact/run_launcher
--- a/Genshin Impact/run_launcher
+++ b/Genshin Impact/run_launcher
@@ -1,56 +1,88 @@
 #!/bin/bash
+set -e
 
-# Ensuring winetricks is installed.
-if ! type -t "winetricks" &> /dev/null; then
-    read -p "Winetricks is not installed. We've a winetricks installer built-in. You want to proceed with the installation? ([y]es or [N]o): "
-    case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
-        y|yes) install_wine_tricks ;;
-        *) exit 0 ;;
-    esac
-fi
+OS_RELEASE_FILES=("/etc/os-release" "/usr/lib/os-release")
 
-# Ensuring Wine is installed.
-if ! type -t "wine" &> /dev/null; then
-    echo "Wine is not installed. We highly recommend installing the staging build."
-    exit 0
-fi
+for release in ${OS_RELEASE_FILES[@]} ; do
+    if [[ ! -e "$release" ]]; then
+        continue
+    fi
+    DISTRO=$(sed -rn 's/^NAME=(.+)/\1/p' "$release" | sed 's/"//g')
+done
 
-# Install winetricks in any distro.
-function install_wine_tricks() {
-    # Checking if the distro is Debian-based
-    if [ -f "/etc/debian_version" ]; then
-        echo "We have detected that the distribution in use is based on Debian. Proceeding with the winetricks installation..."
-        sudo apt-get install winetricks
-    else
-        # Checking for other distros
-        DISTRO_INFO="$(cut -d "=" -f2- <<< "$(cat /etc/*-release | grep DISTRIB_ID)")"
-        case $(echo $DISTRO_INFO | tr '[A-Z]' '[a-z]') in
-            arch|manjaro)
-                echo "We have detected that the distribution in use is based on Arch Linux. Proceeding with the winetricks installation..."
-                sudo pacman -Syy winetricks ;;
-            *)
-                echo "There is not built-in support for $DISTRO_INFO. Proceeding with standard installation."
-                echo "This may be a little bit harder way to update their packages in the future."
-                wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
-                chmod +x winetricks
-                sudo mv winetricks /usr/bin/
-        esac
+escape_code() {
+    echo "\033[$1m"
+}
+
+SUCCESS_PREFIX="$(escape_code "0;32")✓$(escape_code 0)"
+QUESTION_PREFIX="$(escape_code "0;36")❓$(escape_code 0)"
+ERROR_PREFIX="$(escape_code "0;31")❌$(escape_code 0)"
+
+load_properties() {
+    . ./variables.exports
+    echo -e "$SUCCESS_PREFIX Loaded properties on $(uname -om)."
+}
+
+dependencies() {
+    function join {
+        local IFS="$1"
+        shift
+        echo "$*"
+    }
+
+    declare -a MISSING_DEPENDENCIES
+
+    type winetricks &> /dev/null || MISSING_DEPENDENCIES+=("winetricks")
+    [ ! -f "$WINE_BIN" ] && MISSING_DEPENDENCIES+=("wine")
+
+    if (( ${#MISSING_DEPENDENCIES[@]} )); then
+        read -p "$(echo -e "${QUESTION_PREFIX}We found ${#MISSING_DEPENDENCIES[@]} missing dependencies. You want to install automatically? (y/N): ")" prompt
+        if [[ $prompt =~ [yY](es)* ]]; then
+            local all=$(join " " ${MISSING_DEPENDENCIES[@]})
+            case $DISTRO in
+                "Arch Linux"|"Manjaro Linux")
+                    INSTALL_STATEMENT="pacman -S" ;;
+                *"buntu"|"Linux Mint"|"Debian*"|"Zorin OS"|"Pop!_OS"|"elementary OS"|"KDE neon")
+                    INSTALL_STATEMENT="apt install" ;;
+                "Fedora")
+                    INSTALL_STATEMENT="dnf install" ;;
+                "openSUSE"*)
+                    INSTALL_STATEMENT="zypper install" ;;
+                "Solus")
+                    INSTALL_STATEMENT="eopkg it" ;;
+                *)
+                    echo -e "$ERROR_PREFIX Could not install dependencies automatically. Missing: $all"
+                    exit -1 ;;
+            esac
+            sudo $INSTALL_STATEMENT $all
+        fi
     fi
 }
 
-if ! [ -e "./_installer.exe" ]; then
-    wget -O _installer.exe "https://ys-api-os.mihoyo.com/event/download_porter/link/ys_global/genshinimpactpc/default"
-fi
-
-. ./common
-
-# Create Wine prefix and execute installer.
-if ! [ -d "$WINEPREFIX" ]; then
-    # Setup required dependencies.
-    winetricks --unattended vcrun2019 arial
+install_again() {
+    winetricks --unattended --force vcrun2019 arial
     "$WINE_BIN" "$PWD/_installer.exe"
+}
+
+launch() {
+    if ! [ -e "./_installer.exe" ]; then
+        wget -O _installer.exe "https://ys-api-os.mihoyo.com/event/download_porter/link/ys_global/genshinimpactpc/default"
+    fi
+    # Create Wine prefix and execute installer.
+    if ! [ -d "$WINEPREFIX" ]; then
+        # Setup required dependencies.
+        install_again
+    fi
+
+    LAUNCHER_PATH="$WINEPREFIX/drive_c/Program Files/Genshin Impact/launcher.exe"
+    "$WINE_BIN" "$LAUNCHER_PATH"
+}
+
+if [ -x "$DISTRO" ]; then
+    echo  -e "$ERROR_PREFIX Could not detect your operational system. You will be not able to install dependencies through this script."
 fi
 
-"${WINE_BIN}server" -k
-LAUNCHER_PATH="$WINEPREFIX/drive_c/Program Files/Genshin Impact/launcher.exe"
-"$WINE_BIN" "$LAUNCHER_PATH"
+load_properties
+dependencies
+[ "$1" == "install" ] && install_again
+launch
